version: '2'

services:
  php:
    build:
      context: ./php
      args:
        USER_NAME: 'hahoang'
        UID: '1000'
    container_name: php
    restart: always
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      docker-lamp:
  httpd:
    build:
      context: ./httpd
    container_name: httpd
    restart: always
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker
      - ./public_html/:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker-lamp:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ./public_html/:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    privileged: true
    networks:
      docker-lamp:
        ipv4_address: 10.5.0.9
  mariadb:
    image: mariadb:10.3
    container_name: maziadb
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: "1"
    ports:
      - "3306:3306"
    networks:
      docker-lamp:
        ipv4_address: 10.5.0.6
networks:
  docker-lamp:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
